namespace AlmaNet.Emotion
{
    public enum EmotionType
    {
        None,
        Admiration,
        Anger,
        Disliking,
        Disappointment,
        Distress,
        Fear,
        FearsConfirmed,
        Gloating,
        Gratification,
        Gratitude,
        HappyFor,
        Hate,
        Hope,
        Joy,
        Liking,
        Love,
        Pity,
        Pride,
        Relief,
        Remorse,
        Reproach,
        Resentment,
        Satisfaction,
        Shame,
    }
}